### ISSUE TITLE
Can you use this without JSPM?

### ISSUE THREAD

**Issue by hrajchert** [peteruithoven/systemjs-debugger#5]
Hi, i'm having trouble trying to understand how System.js loads a bundle I created manually. I use gulp, to create my bundles, can I use this debugger directly with System.js? How can I tell System.js to know how to locate `System.import('systemjs-debugger')`?

Thanks!

**Comment by peteruithoven** [comment]
I'm afraid I've never tried it without JSPM, so really I have no idea. 
For me something like `systemjs-debugger` is probably recognized because my `jspm.config.js` contains configuration that maps it to `github:peteruithoven/systemjs-debugger@0.0.6`, and `github:` is mapped to `jspm_packages/github/`. This means  `systemjs-debugger` is translated into `jspm_packages/github/peteruithoven/systemjs-debugger@0.0.6`. What happens when you try the full path to the package? 

I'm not sure how gulp bundles, because that's just a task runner? What does the transpilation and bundling part?

**Comment by hrajchert** [comment]
Thanks for the data! I ended up solving the issue with manual debugging :D
